---
name: JupyterLabPyscript
version: "0.0.1"
slug: jupyterlabpyscript
description: Customized jupyterlab addon with support for Pyscript
url: https://github.com/iot49/addon-jupyterlab-pyscript
codenotary: ttmetro@leaf49.org
ingress: true
panel_icon: mdi:flask-outline
arch:
  - aarch64
  - amd64
homeassistant_api: true
init: false
map:
  - config:rw
  - share:rw
options:
  github_access_token: ""
  system_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  github_access_token: password
  system_packages:
    - str
  init_commands:
    - str
